### PR TITLE
Add new resource

### LINKED ISSUE #86: [Feature] Add a new resource
## Problem
Add a presentation explaining copyright and creative commons.

## Description
While reading through the style guide I came across a really well made presentation explaining everything about copyright and creative commons made in canva. I think that this should be added as a resource and should also be in the featured Top 16.

image
## Additional context
Here is the link to the presentation being discussed
[Canva Link](https://www.canva.com/design/DADm40hSwIU/9yEhtLnl5O1WMKbx8JSSkA/watch?utm_content=DADm40hSwIU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

## Implementation
- [x] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by nown1ne**
## Fixes
Fixes #86  by @nown1ne

## Description
Adds the Canva Slides Resource discussed in the issue

## Technical details
Discuss the ```weight``` and ```featured``` for this file and update the others
!! The permalink works but the resource isn't visible in the featured or all pages !!!

## Screenshots
image
image

## Checklist
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by justaskulkarni** [comment]
@nown1ne I saw your branch. The resource should be inside the docs folder. 
image

**Comment by nown1ne** [comment]
Oh yes 
Thank you so much for helping !

But it still doesn't show up :(
I also tried giving it weight(24) and featured(12) which would be the values for the last resource, it won't show up.

**Comment by nown1ne** [comment]
After restarting the Docker server, it appeared in the featured and all listings.
image

**Comment by possumbilities** [comment]
Addressed by:
*  #224

**Pull request closed without merging**
