### PR TITLE
Added the HTML lang attribute to the HTML documents

### LINKED ISSUE #128: [Bug] Add HTML lang attribute to HTML files
## Description
The HTML files do not contain an HTML lang attribute which is neccessary because it helps search engines  to return language-specific results on the SERP.

## Reproduction
Open to the HTML files

## Expectation
This will help to improve the interpretation of the page content by users in different locales.

## Resolution

- [x] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by JennySimen**
## Fixes

Fixes #128  by @JennySimen

## Description
This PR adds the HTML lang attribute at the top of the HTML document which is neccessary because it helps search engines to return language-specific results on the SERP and improves the accessibility of the website.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by justaskulkarni — APPROVED** [review]
All 3 files which needed to be changed have been changed. Nice work @JennySimen.

**Comment by possumbilities** [comment]
@JennySimen Hi! Thanks so much for this contribution! 

I think the lang attribute is supposed to be on the `<html>` element, rather than the `<head>` element.

**Comment by possumbilities** [comment]
@JennySimen Hi again! Offering a reminder that there's a change pending for this to move to Approval. 

(If it's not addressed soon I'm going to close the PR.)

**Comment by JennySimen** [comment]
Hi @possumbilities I will look into the changes

**Comment by possumbilities** [comment]
@JennySimen Thank you! ❤️

**Comment by possumbilities** [comment]
For more context as to where to apply it, please see this in the official spec:

https://www.w3.org/International/questions/qa-html-language-declarations

**Comment by possumbilities** [comment]
@JennySimen Did you mean to close this?

**Comment by JennySimen** [comment]
@possumbilities No I didn't

**Review by possumbilities — APPROVED** [review]
@JennySimen Great work! Thank you so much for the contribution. ❤️

**Pull request merged**
