### PR TITLE
Fix # append in url on pressing back

### LINKED ISSUE #81: [Bug] Href # Link on page Requires back button to be hit twice on browser
## Description
After selecting the desired filters to display the resources, If I hit the back button on the browser I have to hit it twice to get back to the previous page.

## Reproduction

1. You click on any medium . Let's say "video"
2. Then you click on any language. Let's say "EN"
3. Press the back button to get back to the previous page.
4. See error.

## Expectation
It should display me all the resources that are under "video".

## Screenshots
Step1:
issue2 1
Step2:
issue2 2
AND THE MOMENT I HIT BACK BUTTON ON MY BROWSER IT DISPLAYS NOTHING!!
issue2 3

## Environment
Not environment specific

## Resolution

- [x] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by Xaid-vfx**
## Fixes

Fixes #81 by @nishchay-veer 

## Description
On selecting two filters and then pressing back, there is no '#' appended in the url.
This issue was occuring because there was `href="#"` provided in the `<a>` tag. Since the url is already set using `onclick="window.location.search..` , the href can be set to `javascript:;`.

## Screenshots
Selecting two filters:
Screenshot 2023-07-19 at 10 28 00 PM

On pressing back:
Screenshot 2023-07-19 at 10 28 29 PM

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Xaid-vfx** [comment]
@possumbilities this PR also resolves the path for #169

**Comment by Xaid-vfx** [comment]
@possumbilities could you review this?

**Comment by isabelxklee** [comment]
Hi @Xaid-vfx! 👋🏼 I'm curious if this issue is still being worked on / reviewed, considering that the bug is still visible on the live site. 👀 From reading https://github.com/creativecommons/cc-resource-archive/issues/81 and https://github.com/creativecommons/cc-resource-archive/pull/169, it looks like this PR will fix a few issues!

**Comment by Xaid-vfx** [comment]
> Hi @Xaid-vfx! 👋🏼 I'm curious if this issue is still being worked on / reviewed, considering that the bug is still visible on the live site. 👀 From reading #81 and #169, it looks like this PR will fix a few issues!

Yeah this PR will resolve the issue but it still needs to be reviewed by maintainers.

**Comment by isabelxklee** [comment]
@Xaid-vfx Okay, sounds good! Thanks for the clarification. ☺️

**Comment by possumbilities** [comment]
@Xaid-vfx 

Is there a reason for not removing the `href` attribute utterly, and setting the anchor to `role=button`, since it's more or less a button and not a link in this situation?

Perhaps paired with something like this? 

```
<a onclick="location.href=location.href.replace(/&?topic=([^&]$|[^&]*)/i, ''); return false;">x</a>]
````

See [w3c guidelines](https://www.w3.org/WAI/ARIA/apg/patterns/button/examples/button/) on various ways to utilize anchors, and how the anchor doesn't have to have an `href`. Doing that might remove the "link" look and feel and there may be further accessibility affordances to consider as well.

I could be wrong, and am I'm open to reasonings.

------

Relatedly, we should probably draft an Issue around how a link/button wrapping the letter `x` isn't the most accessible, and we should be instead wrapping around something more descriptive like `remove filter` and then replacing it with an `x` via Accessible means (like css `content` or something else). I think that's outside the scope of this PR and Issue, but it is very visible after looking at this that we're correcting a behavior around an already poor implementation of a filter removal "button" behavior.

**Comment by isabelxklee** [comment]
> @Xaid-vfx
> 
> Is there a reason for not removing the `href` attribute utterly, and setting the anchor to `role=button`, since it's more or less a button and not a link in this situation?
> 
> Perhaps paired with something like this?
> 
> ```
> <a onclick="location.href=location.href.replace(/&?topic=([^&]$|[^&]*)/i, ''); return false;">x</a>]
> ```
> 
> See [w3c guidelines](https://www.w3.org/WAI/ARIA/apg/patterns/button/examples/button/) on various ways to utilize anchors, and how the anchor doesn't have to have an `href`. Doing that might remove the "link" look and feel and there may be further accessibility affordances to consider as well.
> 
> I could be wrong, and am I'm open to reasonings.
> 
> Relatedly, we should probably draft an Issue around how a link/button wrapping the letter `x` isn't the most accessible, and we should be instead wrapping around something more descriptive like `remove filter` and then replacing it with an `x` via Accessible means (like css `content` or something else). I think that's outside the scope of this PR and Issue, but it is very visible after looking at this that we're correcting a behavior around an already poor implementation of a filter removal "button" behavior.
> 
> @isabelxklee If documenting that Issue is something you'd like to do, please feel free too!

I agree! I also wonder if we can zoom out a bit and consider using a more common UX pattern for implementing the category filters. For example, many category filter UIs use color to indicate active/inactive status, so that users can still see all the filter options. Accessibility-wise, I think this is also great because elements don't unnecessarily jump around on the page.

And yes, down to document this issue!

Example from Thingtesting:
I think they could be more explicit, by adding an "x" icon in the filter button, or a "clear all" button, but I think this is a good example of what I mentioned above.

Screenshot 2024-02-26 at 10 26 16 PM

**Comment by Xaid-vfx** [comment]
@possumbilities I agree with the fact that removing `href` attribute might look more cleaner. You are right about anchor tag doesn't necessarily needs to have an `href`. Thanks for the input, making the changes right away !!

**Review by possumbilities — APPROVED** [review]
@Xaid-vfx I think this all is sufficient, until we improve the overall UX of the filtering behavior. Thank you! Approved!

**Pull request merged**
