### PR TITLE
Expanded the abbreviations of languages

### LINKED ISSUE #87: [Feature] Expanding the abbreviations of languages
## Problem
To increase user experience, I feel the languages should not just be stated in short forms as it may not strike the user or it might take a while to find the language he's looking for. [Happened with me initially]

## Description
So displaying the full name of the language would be great instead of the abbreviation. 

## Alternatives
An alternative would be to just have the languages all directly mentioned using filters.

## Implementation
- [x] I would be interested in implementing this feature.
Here is one way -
image

### PR DESCRIPTION
**Pull request by Javali-M**
## Fixes
Fixes #87 by @Javali-M

## Description
To increase user experience, the language abbreviations have been expanded to display all the names clearly in a bulleted format in two columns.

## Technical details
Formatted the names into an unordered list and set the columns attribute to 2 to display them side by side.

## Screenshots
image

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by adidevs — APPROVED** [review]
This is a good solution @Javali-M ! The languages are mapped correctly and it all looks good to me!

**Comment by Javali-M** [comment]
Thank you @adidevs😊

**Review by adidevs — CHANGES_REQUESTED** [review]
Hey @Javali-M I need to tell you that this issue requires a lot more work. 
1. The code in the `all.html` needs to be changed as well
2. Just changing the string in the `languages.yml` file causes the code to break and the filters do not work. The reason being that the language codes need to be changed in individual resources too. 

A better approach could be finding a way to implement the same using the convention used in the `topics.yml` file, i.e. `name` & `string`

As a first step you can convert this PR to a draft PR and implement these changes. Thank you!

**Comment by Javali-M** [comment]
@adidevs Right, that was a mistake on my part, I've corrected it now. The filters are working all fine. I used the `name ` and `string ` format for the [languages.yml](https://github.com/creativecommons/cc-resource-archive/blob/main/docs/_data/languages.yml) file. 
Thank you for the feedback!

**Comment by adidevs** [comment]
That is great @Javali-M , I suggest you add a short sample workflow video so as to demonstrate the functionality and that the filters are working so that the changes can be verified. Thank you.

**Comment by Javali-M** [comment]
Here is the workflow video showing both the original website and my implementation side by side. I'm selecting the same languages on both tabs to show the functionality working correctly.

https://user-images.githubusercontent.com/78152931/226164647-e249f1ba-e662-4ff2-a117-7b64293eaebf.mp4

**Review by adidevs — COMMENTED** [review]
The functionality has been restored and language filters are working fine after the recent changes. Looks good to me!
It would be best to await comments from a maintainer for a final approval. Good work @Javali-M !

**Comment by Javali-M** [comment]
@possumbilities then I suppose we'll have to change the topic short forms post filter as well? 
image
And if I change the `document.write(language)` to `document.write(language.name)` it shows up as undefined. So the other approach would involve changing the language strings of all the individual resources as well. Along with the changing the all the abbreviations to full names in order to make the filters work.
image

**Comment by possumbilities** [comment]
@Javali-M That's a good point. I think what might be best is to do the original route you suggested where the abbreviation still shows up post-filter, make a PR for that get it through. 

And then make a new Issue to address expanding the abbreviation post filter as a further improvement?

Thoughts?

**Comment by Javali-M** [comment]
@possumbilities, right I think that's best. I think we should merge this PR for now and create a new one for further enhancements so that others can also suggest better approaches to solve that issue. 
Thanks!

**Review by adidevs — APPROVED** [review]
@Javali-M This satisfies the current requirement and can be merged. The solution for the post filter language code show up matches the approach I had in mind. Looks good to me!

**Review by possumbilities — APPROVED** [review]

**Pull request merged**
