### PR TITLE
Filters full name displayed on Selection

### LINKED ISSUE #91: [Feature] The Selected Filters are not displayed properly. Short forms are displayed.
## Problem
On selecting any specific Topic , Medium or Language. The selected niche is not displayed properly. Short forms are often displayed.

## Description
For example, On selecting  `Open Educational Resources ` , `oer` is displayed.
Check the following image:

Screenshot 2023-03-19 at 5 48 04 AM

This decreases User Experience and can be replaced by displaying actual Names of Filters.
Check the following image:

Screenshot 2023-03-19 at 5 48 59 AM

## Alternatives
A good alternative is that instead of removing the entire list of filters and displaying just the selected one, we can keep the entire list as it is and just highlight the selected filters using CSS.

## Implementation

- [x] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by Xaid-vfx**
## Fixes

Fixes #91  by @xaid-vfx

## Description
On selecting any specific filter, the full name of the selected filter is displayed.

## Tests

To verify, Select any filter. For example : `Open Educational Resources` after being selected will display `Open Educational Resources` not `oer` as earlier.

## Screenshots

Before:
Screenshot 2023-03-19 at 5 48 04 AM

After:

Screenshot 2023-03-19 at 5 48 59 AM

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by justaskulkarni** [comment]
Great work @Xaid-vfx 
The only problem that occurs out here is:
Current:
image
After your PR:
image
Even the current functionality has the [issue](https://github.com/creativecommons/cc-resource-archive/issues/81) about the display of # along with filter name.

**Comment by Xaid-vfx** [comment]
This issue can be easily fixed by adding an extra or condition inside if statement like this:
Screenshot 2023-04-07 at 3 29 38 PM

 But I wouldn't recommend doing this because creating an edge case for a bug might not be the best approach. Also,on pressing back there are **no results**, there's **no point in displaying the filter name**. See below:

Screenshot 2023-04-07 at 3 52 25 PM

This is misleading, since it shows **Licenses** being selected but there are **no results** for it. 

I think the best option is this case is to fix #81 as soon as possible. If maintainers allow it, I would be happy to fix #81 since there is no activity there.

Let's see what maintainers have to say about this.

**Comment by Xaid-vfx** [comment]
Hey @possumbilities ,
Could you check this PR?

**Comment by possumbilities** [comment]
@Xaid-vfx Thinking through it, I tend to agree that fixing #81 would likely sort things out much better. And then proceed further into any adjacent remaining issues.

**Comment by Xaid-vfx** [comment]
@possumbilities I have resolved the conflicts on this branch and the issue #81 is resolved as well which makes this PR
ready to reviewed and merged

**Review by possumbilities — APPROVED** [review]
Great work! Thank you! ❤️

**Pull request merged**
