### PR TITLE
Added doctype Html to the top of the document

### LINKED ISSUE #33: [Bug] Entire CC-resource-archive page is running on quirks mode
## Description
Quite strangely the whole CC-resource-archive page is running on `quirks` mode as the `Doctype` Tag is missing from the Page, being in quirks mode can make the page not serving the modern HTML and CSS efficiently 

## Reproduction

open the CC-archive site and open the console

## Screenshots
Home _ Creative Commons Resource Archive — Mozilla Firefox 2_24_2023 8_42_26 PM

## Environment

 - Device: (_eg._ iPhone Xs; laptop)
 - OS: (_eg._ iOS 13.5; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Version: (_eg._ 13; 73)
 - Other info: (_eg._ display resolution, ease-of-access settings)

## Resolution

- [x] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by Biki-das**
## Fixes

Fixes #33 

## Description
This PR adds the Doctype html to the top of the html document, such that our html page gets rendered in the Standard mode rather than in quirks mode, as all the modern html and css standards are expected to perform well in the Standard mode

## Screenshots

https://user-images.githubusercontent.com/72331432/226085918-6f278db9-28d1-4ce5-847e-2da5a4c7485b.mp4

The console does not show the quirks mode warning now 
## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by adidevs — CHANGES_REQUESTED** [review]
Hey @Biki-das, that was indeed a nice find from your end. 
However I would suggest you to add the same to the `layouts/resource.html` as well so as to cover those pages as well. This will make the solution complete.

**Comment by possumbilities** [comment]
@Biki-das I'm going to +1 to what @adidevs suggested! (Thanks for that input ❤️ )

**Review by arimallick — APPROVED** [review]

**Review by arifhossain512 — APPROVED** [review]

**Comment by possumbilities** [comment]
@Biki-das re-upping my previous comment!

**Review by possumbilities — APPROVED** [review]
Thank you! 💯

**Pull request merged**
