### PR TITLE
#62 Reduced the download button size

### LINKED ISSUE #62: [Feature] Reduce the download button size
## Problem

- Currently the download button in all the pages is very large in size, and doesn't look much appealing. 
- "[Creative Commons Licenses for Non-Profit Organizations](http://vimeo.com/84880520) from [BCcampus](http://vimeo.com/bccampus) on [Vimeo](https://vimeo.com/)", I think the placement of this content can be better.
Screenshot from 2023-03-05 20-38-56

## Description
- Reducing the size or redesigning the button can help.
- we can place the described content either in the description box or may be remove it(as there is repetition )

## Additional context
Not sure but the download button rather than downloading content just redirects to different websites or broken links.
Is this how these buttons are supposed to work?

## Implementation

- [x] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by das123s**
## Fixes

Fixes #62 by @Aaishpra

## Description
reduced the download button size

## Technical details
changes made on style.ss file

## Tests
1. Visit homepage of creative commons.
2. Find the resource list.
3. Click on any of the resources.
4. Check the view in detail button size.

## Screenshots
Image 2024-04-01 at 9 49 34 PM
WhatsApp Image 2024-04-01 at 11 11 38 PM)

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by possumbilities — APPROVED** [review]
Hi! Thanks for this. Approved. 

(if you comment on the Issue attached to this I can assign you to it as well)

**Comment by das123s** [comment]
> Hi! Thanks for this. Approved.
> 
> (if you comment on the Issue attached to this I can assign you to it as well)

yes, Can you please assign to me.

**Comment by possumbilities** [comment]
@das123s you would need to go to #63 and comment there for me to do so.

**Comment by possumbilities** [comment]
@das123s I see that I accidentally listed 63, instead of 62. #62 is the one you'd need to comment on. Apologies for the mistake.

**Comment by das123s** [comment]
> @das123s I see that I accidentally listed 63, instead of 62. #62 is the one you'd need to comment on. Apologies for the mistake.

No it's ok. I have done the comment on issue #62.

**Pull request merged**
