### PR TITLE
fix: fixed missing anchor tag in resource.html

### LINKED ISSUE #111: Unnecessary <a> tags in resource page
## Description
Unnecessary <a> tags are used in all the resource pages.

## Reproduction
1. open docs folder
2. then navigate to _site folder
3. all the index.html files in each folder contains this error ( specifically while rendering the title for the page )
4. See error.
5. This is also seen in the resource.html in the _layout file.

## Expectation
remove this redundant a tag as it not only confuses the reader but disrupts the intended working of the website

## Screenshots
image
Screenshot from 2023-03-25 00-51-30

## Resolution
- [x] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by C-NikhilKarthik**
## Fixes
Fixes #111  by @C-NikhilKarthik

## Description
Fixed the anchor tag that was not closed , along with the wrong h3 closing a h2 tag.

## Technical details
I have fixed the resource.html file in _layout folder that had the following issue :

1. Anchor tag enclosing the Title of the page was not enclosed
2. The h2 that was wrapping the above mentioned Anchor tag was incorrectly enclosed using a h3 tag.

## Screenshots
image

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Lakshay-Pruthi** [comment]
@C-NikhilKarthik You were supposed to remove the anchor tag.

**Review by adidevs — CHANGES_REQUESTED** [review]
@C-NikhilKarthik Good work fixing the h2 tag and kudos to @Lakshay-Pruthi for highlighting the same in the issues.

+1 to @Lakshay-Pruthi , the idea behind the same is that the user is already on the resource page and creating a hyperlink to the same resource is not needed. Also, the anchor tag you created does not have an href attribute I am afraid.

I suggest you remove the anchor tag altogether and that shall fix your PR.

**Comment by C-NikhilKarthik** [comment]
The adjustments stated above have been incorporated to the most recent commit. Review the document and provide the necessary feedback @adidevs @possumbilities @Lakshay-Pruthi .

**Review by adidevs — APPROVED** [review]
Changes made as requested! Looks good to me! Good work @C-NikhilKarthik

**Review by possumbilities — APPROVED** [review]
@C-NikhilKarthik Thank you for this! ❤️

**Pull request merged**
