### PR TITLE
Code Organized with proper indentation and comments

### LINKED ISSUE #101: [Feature] <Organise code with proper indentation and comments>
## Problem
The current code in the repository is not well defined, organized and commented

## Description
I plan to organize the code structure with the standard rules and indentation. Comments can be added to help future contributors to know which code does what.

For example:

## Implementation

- [ ] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by Xaid-vfx**
## Fixes

Fixes #101 by @xaid-vfx
- #101 

## Description
The code structure has been arranged in compliance with standard formatting conventions and indentation. Furthermore, comments have been added to specific areas within the code to assist future developers in locating and contributing to it with ease.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by justaskulkarni** [comment]
Hey @Xaid-vfx, there is still a bit more work needed before this PR can be merged. 
The code structure in docs/submission.html also needs to be organized with proper indentation and comments.

**Review by soustab10 — APPROVED** [review]

**Comment by possumbilities** [comment]
@Xaid-vfx Usually the head area isn't indented, and a few files might be missing "End of line" characters. 

Also need to resolve the merge conflicts, but other than that once the above is run through again this would likely be approvable. Well done!

**Comment by Xaid-vfx** [comment]
> @Xaid-vfx Usually the head area isn't indented, and a few files might be missing "End of line" characters.
> 
> Also need to resolve the merge conflicts, but other than that once the above is run through again this would likely be approvable. Well done!

Hey @possumbilities,
I might sound dumb but could you give an example of `few files might be missing "End of line" characters`. I couldn't quite grasp what you meant there exactly.

**Comment by possumbilities** [comment]
> > @Xaid-vfx Usually the head area isn't indented, and a few files might be missing "End of line" characters.
> > Also need to resolve the merge conflicts, but other than that once the above is run through again this would likely be approvable. Well done!
> 
> Hey @possumbilities, I might sound dumb but could you give an example of `few files might be missing "End of line" characters`. I couldn't quite grasp what you meant there exactly.

@Xaid-vfx 

If you view the files tab on this PR you can see a little red circle with a line through it at the end of some of the files: 
Screen Shot 2023-07-11 at 2 23 45 PM

This means it's missing an `end of file` character, which you can have your editor automatically add when editing/saving files.

**Comment by Xaid-vfx** [comment]
@possumbilities Thank you so much. I'll update this PR asap.

**Comment by Xaid-vfx** [comment]
@possumbilities Since this PR was raised long time back, its branch is 43 commits behind and has a few conflicts. Should I raise a new PR with a new branch (this way all the new code would be organized as well) or just push the changes without merging 43 commits?

**Comment by possumbilities** [comment]
@Xaid-vfx You should be able to work through resolving the merge conflicts and keep this PR. But you can also close this PR and start a fresh one since its so far behind. 

I'd suggest trying to resolve the conflicts, first though. It _should_ be possible.

**Comment by possumbilities** [comment]
@Xaid-vfx do you intend to resolve the conflicts and move this out of Draft?

**Pull request closed without merging**
