### PR TITLE
Added_footer

### LINKED ISSUE #34: Add a Footer to the page
## Problem

Currently, the bottom of the page looks a bit odd. 

## Description

Adding a footer there will improve the look and feel of the page and it will also match the  current CC aesthetics

## Implementation

- [x] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by nandu-99**
Fixes #34  by @tinniaru3005

## Description
The issue #34 has been resolved by adding a footer to the page. The footer design has been inspired by the original website of Creative Commons to maintain consistency. Additionally, the Twitter icon has been updated to enhance the overall design and functionality.

## Screenshots
Screenshot 2024-03-08 at 11 14 29 AM

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by possumbilities** [comment]
@nandu-99 Hi! Thanks for this contribution! ❤️ 

This is not a 1-to-1 implementation of the code in the footer that's currently utilized. It should follow the exact HTML markup and the rendered output should match what is presently visible on CreativeCommons.org. To achieve that there may be a need to use a localized CSS file to correct items local to this repository.

Also, adding the Twitter logo would have to happen here, and this issue is currently `status: blocked`: 
* https://github.com/creativecommons/index-prototype/issues/48

**Comment by nandu-99** [comment]
@possumbilities Thank you for your feedback! I've implemented the required changes and made sure to closely follow the existing HTML markup to match the rendered output of CreativeCommons.org. Additionally, I've kept the separate CSS file as suggested.

Regarding the logo of Twitter, I've reverted it back to its original state to ensure consistency with the website.

Could you please review the changes and provide any further feedback or suggestions? Your input is highly appreciated!

**Comment by possumbilities** [comment]
Hi @nandu-99 that's all much better. I would also recommend the following changes as well to be closer to the implementation of CreativeCommons.org: 
* include the entire `vocabulary` directory in a sensible location to import from. You can find it in [index-prototype](https://github.com/creativecommons/index-prototype/tree/main/src/vocabulary). This will ensure that relevant fonts are present as well, and make it easier to sync updates locally from vocabulary later.
* Rather than a `<link>` in the html, I'd suggest including it the same way its done with an `@import` and a `@layer` in a `style.css` file see [vocabulary-theme](https://github.com/creativecommons/vocabulary-theme/blob/f3fc33e2a2ea9de6b2b79b7b161ecfef4a12d0f7/src/style.css#L14)

**Comment by possumbilities** [comment]
I believe #206 resolved this. Closing, thanks for your contribution!

**Comment by Murdock9803** [comment]
@TimidRobot So will this issue be assigned to me ?

**Pull request closed without merging**
