### PR TITLE
Fixes #299 Add "Infographic" to the documentation about media in resourcetemplate.md

### LINKED ISSUE #299: [Feature] Add "Infographic" to the documentation about media in  resourcetemplate.md
## Problem

For the submission of resources, in the `resourcetemplate.md` file, there is a description about available options to choose from, for the `medium` of resource. But there are total 5 options documented. At present there are total of six options available.

## Description

Including the `Infographic` option will help the users to categorize the resource properly and will also be significant, as we already the option in our site. It is just not included in the documentation.

## Additional context

The current resource template file can be accessed [here](https://github.com/creativecommons/cc-resource-archive/blob/main/resourcetemplate.md)
On line 76 of the file, there is description of the medium category. there are 5 options present.

## Implementation

- [x] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by lokendra005**
## Fixes

- Fixes #299 by @Murdock9803

## Description

 In the resourcetemplate.md file, there is a description about available options to choose from, for the medium of resource. But there were total 5 options documented. This pull request ensures that the sixth option is present as well.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the default branch of the repository (main or master).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

</details>

### CODE REVIEW

**Comment by Murdock9803** [comment]
@lokendra005 please provide a clear description to your Pull Request. You can read the guidelines [here](https://opensource.creativecommons.org/contributing-code/pr-guidelines/).

**Comment by lokendra005** [comment]
> @lokendra005 please provide a clear description to your Pull Request. You can read the guidelines [here](https://opensource.creativecommons.org/contributing-code/pr-guidelines/).

Added the description, kindly check.

**Comment by lokendra005** [comment]
@Murdock9803  kindly review!!
And do let me know if further changes are required.

**Review by Murdock9803 — APPROVED** [review]
This looks good to me. @possumbilities please have a look 🙌

**Comment by lokendra005** [comment]
@possumbilities Please review !!

**Comment by lokendra005** [comment]
@possumbilities any updates !!

**Pull request merged**
