### PR TITLE
Fixed overlapping text on languages list on home page

### LINKED ISSUE #223: [Bug] Overlapping Text in Languages list on Home Page
## Description
In the Languages list on the home page, the list items for Armenian and Russian languages are overlapping each other, which can cause readability issues and potential confusion for users and hence not approaching towards a better user experience.

## Reproduction
1. Go to https://resources.creativecommons.org/
2. In the languages list you can observe the overlap between Armenian and Russian language text.

## Expectation
Each language listed in the Languages section should be displayed clearly and distinctly, without any overlap or interference from other languages.

## Screenshots
Screenshot from 2024-03-19 17-42-13

## Environment
 - Device: (laptop)
 - OS: (Ubuntu 20.04)
 - Browser: (Firefox)
 - Version: (122.0.1)
 - Other info: (checked in all the screen sizes/zooms)

## Resolution

- [x] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by praveen-rikhari**
## Fixes

Fixes #223 by @praveen-rikhari

## Description

Resolved overlapping issue in the Languages section on the home page. The Armenian and Russian language list items were previously overlapping each other, affecting readability. This PR fixes the layout to ensure proper spacing and alignment between the languages. Users can now view the Languages section without any overlapping text.

## Technical details

Implemented inline styles on the `<ul>` tag, including `column-gap: 35px;`, alongside existing `columns: 2;`, to address the overlapping issue in the Languages section. This adjustment ensures proper spacing and readability.

#### Before :
Screenshot from 2024-03-19 17-42-13

#### After :
Screenshot from 2024-03-21 16-49-08

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by praveen-rikhari** [comment]
Hello @TimidRobot @annatuma. Hope you are doing great.Please review this PR and let me know if any changes are required.
Thanks

**Review by Xaid-vfx — CHANGES_REQUESTED** [review]
There are so many file changes which are not quoted in issue #223. Your PR should only have those changes which were quoted in the respective issue and approved by the maintainers.

**Comment by praveen-rikhari** [comment]
@Xaid-vfx  Thanks for reviewing this. Please check again is there any more issues in my commits/PR.

**Review by possumbilities — APPROVED** [review]
Thankyou for this contribution! Approved.

**Comment by praveen-rikhari** [comment]
Thankyou @possumbilities.

**Pull request merged**
