### PR TITLE
Added new resource(An explanation of CC)

### LINKED ISSUE #86: [Feature] Add a new resource
## Problem
Add a presentation explaining copyright and creative commons.

## Description
While reading through the style guide I came across a really well made presentation explaining everything about copyright and creative commons made in canva. I think that this should be added as a resource and should also be in the featured Top 16.

image
## Additional context
Here is the link to the presentation being discussed
[Canva Link](https://www.canva.com/design/DADm40hSwIU/9yEhtLnl5O1WMKbx8JSSkA/watch?utm_content=DADm40hSwIU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

## Implementation
- [x] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by praveen-rikhari**
## Fixes

Fixes #86 by @nown1ne 

## Description
Added new/latest resource which consist of informative slide deck covering everything you need to know about copyright and Creative Commons.

## Screenshots
Screenshot 2024-03-20 at 07-33-33 All Creative Commons Resource Archive(1)
Screenshot 2024-03-20 at 08-00-25 An Explanation of Creative Commons Creative Commons

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by praveen-rikhari** [comment]
Hi! @possumbilities @TimidRobot  Please have a look and review my PR and advise if any changes are needed? Your guidance is strongly required.

Thanks

**Comment by possumbilities** [comment]
Hi @praveen-rikhari thanks for this contribution, you need to remove the change you committed for `Gemlock.file`.

**Comment by praveen-rikhari** [comment]
Thanks @possumbilities for your consideration.Yes working on it

**Comment by praveen-rikhari** [comment]
Hey @possumbilities I commited the changes. Please review and let me know if any other changes required.
Thanks

**Review by possumbilities — APPROVED** [review]
Thank you for this contribution! Approved.

**Comment by possumbilities** [comment]
@praveen-rikhari If you comment on the original Issue I'll Assign you there.

**Pull request merged**
