### PR TITLE
organised_code_with_proper_indentation_&_comments

### LINKED ISSUE #101: [Feature] <Organise code with proper indentation and comments>
## Problem
The current code in the repository is not well defined, organized and commented

## Description
I plan to organize the code structure with the standard rules and indentation. Comments can be added to help future contributors to know which code does what.

For example:

## Implementation

- [ ] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by nandu-99**
## Fixes
Fixes #101 by @Xaid-vfx 
- #101 

## Description
The code is clear and easy to follow:
    - It follows common formatting and indentation styles.
    - Comments are included in key areas to help other developers understand and contribute to the code.

## Screenshots
#before
Screenshot 2024-03-03 at 12 38 42 AM
#after
Screenshot 2024-03-03 at 12 38 30 AM

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by BalrajDhakad — CHANGES_REQUESTED** [review]
In the last file wanna-work-together.html you have properly made corrections, the angle bracket of the anchor tags are hanging.

This is the screenshot highlighting the errors:-

anchor

**Comment by nandu-99** [comment]
@BalrajDhakad Thank you, errors resolved👍

**Review by BalrajDhakad — APPROVED** [review]
Good work 👍 
Keep it up

**Comment by possumbilities** [comment]
@nandu-99 You're missing an End of File in `docs/copyright-4-educators.html`

**Pull request closed without merging**
